
-- the server
CREATE TABLE SERVER
(SERVERID VARCHAR(20) PRIMARY KEY NOT NULL,
 OWNERID VARCHAR(20) NOT NULL
);


-- represents a starboard in a server
CREATE TABLE STARBOARD
(BOARD_ID SERIAL NOT NULL,
 CHANNELID VARCHAR(20) NOT NULL,
 SERVERID VARCHAR(20) NOT NULL,
 PRIMARY KEY (BOARD_ID, SERVERID),
 CONSTRAINT BOARD_BELONG_TO_SERVER FOREIGN KEY (SERVERID)
     REFERENCES SERVER (SERVERID)
     ON DELETE CASCADE
     ON UPDATE CASCADE
);

-- represents a message cache for starboard,
-- this represents a starred message
CREATE TABLE STAR_MESSAGE
(MESGID VARCHAR(20) PRIMARY KEY NOT NULL,
 BOARD_ID INTEGER NOT NULL,
 SERVERID VARCHAR(20) NOT NULL,
 CONSTRAINT BOARD_FOR_MESSAGE FOREIGN KEY (BOARD_ID, SERVERID)
     REFERENCES STARBOARD (BOARD_ID, SERVERID)
     ON DELETE CASCADE
     ON UPDATE CASCADE
);

-- the class in a menu
CREATE TABLE CLASS
(CLASS_NUMBER VARCHAR(10) NOT NULL,
 SCHOOL_NAME VARCHAR(20) NOT NULL,
 CLASS_FULL_NAME VARCHAR(100) NOT NULL,
 CLASS_DESCRIPTION VARCHAR(200) DEFAULT NULL,
 PRIMARY KEY (CLASS_NUMBER, SCHOOL_NAME)
);

-- group the classes together
CREATE TABLE CLASS_GROUP
(GROUP_ID SERIAL NOT NULL PRIMARY KEY,
GROUP_NAME VARCHAR(30) NOT NULL
);

-- connect classes to a generic group
CREATE TABLE CLASS_IN_GROUP_RELATION
(CLASS_NUMBER VARCHAR(10) NOT NULL,
SCHOOL_NAME VARCHAR(20) NOT NULL,
GROUP_ID INT,
PRIMARY KEY (CLASS_NUMBER, SCHOOL_NAME, GROUP_ID),
CONSTRAINT RELATION_TO_CLASS FOREIGN KEY (CLASS_NUMBER, SCHOOL_NAME)
    REFERENCES CLASS (CLASS_NUMBER, SCHOOL_NAME),
CONSTRAINT RELATION_TO_GROUP FOREIGN KEY (GROUP_ID)
    REFERENCES  CLASS_GROUP (GROUP_ID)
 )

-- represents a generic role, name is not supplied.
-- if name of role is required, do it through the discord
-- api
CREATE TABLE I_ROLE
(ROLE_ID VARCHAR(20) PRIMARY KEY
);

-- associated an I_ROLE with an emoji
CREATE TABLE ROLE_ENTRY
(ROLE_ID VARCHAR(20) REFERENCES I_ROLE,
 EMOJI_ID VARCHAR(20) NOT NULL,
 PRIMARY KEY (ROLE_ID, EMOJI_ID)
);
-- each class can have many role associated with it
-- this table associate class information to a ROLE_ENTRY.
-- this ensure the menu table is sufficiently abstracted
CREATE TABLE CLASS_ROLE
(
CLASS_NUMBER VARCHAR(10) NOT NULL,
SCHOOL_NAME VARCHAR(20) NOT NULL,
ROLE_ID VARCHAR(20) NOT NULL,
EMOJI_ID VARCHAR(20) NOT NULL,
PRIMARY KEY (CLASS_NUMBER, SCHOOL_NAME, ROLE_ID),
CONSTRAINT CLS_NUM_SCH_NAME_RELATE_TO_ROLE FOREIGN KEY (CLASS_NUMBER, SCHOOL_NAME)
    REFERENCES CLASS (CLASS_NUMBER, SCHOOL_NAME)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT ROLE_RELATE_TO_CLS FOREIGN KEY (ROLE_ID, EMOJI_ID)
    REFERENCES ROLE_ENTRY (ROLE_ID, EMOJI_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- represents a group of roles, used for menu
CREATE TABLE ROLE_GROUP
(MENU_GROUP_NAME VARCHAR(50) NOT NULL,
 SERVERID VARCHAR(20) NOT NULL,
 CLASS_NUMBER VARCHAR(10) NOT NULL,
 SCHOOL_NAME VARCHAR(20) NOT NULL,
 ROLE_ID VARCHAR(20) NOT NULL,
 EMOJI_ID VARCHAR(20) NOT NULL,
 PRIMARY KEY (MENU_GROUP_NAME, SERVERID),
 CONSTRAINT GROUP_IN_SERVER FOREIGN KEY (SERVERID)
     REFERENCES SERVER (SERVERID)
     ON DELETE CASCADE
     ON UPDATE CASCADE,
 CONSTRAINT ROLE_GROUP_RELATION
     FOREIGN KEY (ROLE_ID, EMOJI_ID)
    REFERENCES ROLE_ENTRY (ROLE_ID, EMOJI_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- connect messages to a menu group

-- represents a menu
CREATE TABLE ROLE_MENU
(MENUMSGID VARCHAR(20) PRIMARY KEY NOT NULL,
 CHANNELID VARCHAR(20) NOT NULL,
 MENU_GROUP_NAME VARCHAR(50) NOT NULL,
 SERVERID VARCHAR(20) NOT NULL,
 CONSTRAINT MENU_BELONG_TO_CLASS_ROLE_GROUP FOREIGN KEY (MENU_GROUP_NAME, SERVERID)
     REFERENCES ROLE_GROUP (MENU_GROUP_NAME, SERVERID)
     ON DELETE CASCADE
     ON UPDATE CASCADE
);

