
-- the server
CREATE TABLE SERVER
(SERVERID VARCHAR(20) PRIMARY KEY NOT NULL,
 OWNERID VARCHAR(20) NOT NULL,
 ADMINROLEID VARCHAR(20) NOT NULL,
 MODROLEID VARCHAR(20) NOT NULL
);


-- represents a starboard in a server

CREATE TABLE STARBOARD
(BOARD_NAME VARCHAR(25) NOT NULL,
 CHANNELID VARCHAR(20) NOT NULL,
 SERVERID VARCHAR(20) NOT NULL,
 PRIMARY KEY (BOARD_NAME, SERVERID),
 CONSTRAINT BOARD_BELONG_TO_SERVER FOREIGN KEY (SERVERID)
     REFERENCES SERVER (SERVERID)
     ON DELETE CASCADE
     ON UPDATE CASCADE
);


-- represents a group of menu in a server
CREATE TABLE MENU_GROUP
(MENU_GROUP_NAME VARCHAR(50) NOT NULL,
 SERVERID VARCHAR(20) NOT NULL,
 MENU_TYPE VARCHAR(10) NOT NULL DEFAULT 'CLASS', -- add enum, class/generic --
 PRIMARY KEY (MENU_GROUP_NAME, SERVERID),
 CONSTRAINT GROUP_IN_SERVER FOREIGN KEY (SERVERID)
     REFERENCES SERVER (SERVERID)
     ON DELETE CASCADE
     ON UPDATE CASCADE
);

-- represents a menu
CREATE TABLE MENU
(MENUMSGID VARCHAR(20) PRIMARY KEY NOT NULL,
 CHANNELID VARCHAR(20) NOT NULL,
 MENU_GROUP_NAME VARCHAR(50) NOT NULL,
 SERVERID VARCHAR(20) NOT NULL,
 CONSTRAINT MENU_BELONG_TO_SERVER FOREIGN KEY (SERVERID)
     REFERENCES SERVER (SERVERID)
     ON DELETE CASCADE
     ON UPDATE CASCADE,
 CONSTRAINT MENU_BELONG_TO_GROUP FOREIGN KEY (MENU_GROUP_NAME, SERVERID)
     REFERENCES MENU_GROUP (MENU_GROUP_NAME, SERVERID)
);



-- represents a message cache for starboard,
-- this represents a starred message
CREATE TABLE STAR_MESSAGE
(MESGID VARCHAR(20) PRIMARY KEY NOT NULL,
 BOARD VARCHAR(25) NOT NULL,
 SERVERID VARCHAR(20) NOT NULL,
 CONSTRAINT BOARD_FOR_MESSAGE FOREIGN KEY (BOARD, SERVERID)
     REFERENCES STARBOARD (BOARD_NAME, SERVERID)
     ON DELETE CASCADE
     ON UPDATE CASCADE
);

-- the class in a menu
-- the class in a menu
CREATE TABLE CLASS
(CLASS_NUMBER VARCHAR(10) NOT NULL,
 CLASS_FULL_NAME VARCHAR(100) NOT NULL,
 SCHOOL_NAME VARCHAR(20) NOT NULL,
 CLASS_DESCRIPTION VARCHAR(200) DEFAULT NULL,
 SERVERID VARCHAR(20) NOT NULL,
 PRIMARY KEY (CLASS_NUMBER, SCHOOL_NAME, SERVERID),
 CONSTRAINT CLASS_IN_SERVER FOREIGN KEY (SERVERID)
     REFERENCES SERVER (SERVERID)
     ON DELETE CASCADE
     ON UPDATE CASCADE
);

CREATE TYPE VALID_ROLE_TYPE AS ENUM('STUDENT', 'TA');

-- relationship between class and class_role, since class already has serverid,
-- this doesn't need to --
CREATE TABLE CLASS_ROLE
(CLASS_NUMBER VARCHAR(10) NOT NULL,
 SCHOOL_NAME VARCHAR(20) NOT NULL,
 SERVERID VARCHAR(20) NOT NULL,
 ROLE_ID VARCHAR(20) NOT NULL,
 ROLE_TYPE VALID_ROLE_TYPE DEFAULT 'STUDENT',
 PRIMARY KEY (CLASS_NUMBER, SERVERID, ROLE_TYPE),

 CONSTRAINT CLASS_NAME_TO_ROLE FOREIGN KEY (CLASS_NUMBER, SCHOOL_NAME, SERVERID)
     REFERENCES CLASS (CLASS_NUMBER, SCHOOL_NAME, SERVERID)
     ON DELETE CASCADE ON UPDATE CASCADE);


-- connect a class to the menu
CREATE TABLE CLASS_IN_MENU_GROUP
(CLASS_NUMBER VARCHAR(10) NOT NULL,
 SCHOOL_NAME VARCHAR(20) NOT NULL,
 MENU_GROUP_NAME VARCHAR(50) NOT NULL,
 SERVERID VARCHAR(20) NOT NULL,

 PRIMARY KEY (CLASS_NUMBER, SCHOOL_NAME, MENU_GROUP_NAME, SERVERID),
 CONSTRAINT CLASS_WITH_MENU FOREIGN KEY (CLASS_NUMBER, SCHOOL_NAME, SERVERID)
     REFERENCES CLASS (CLASS_NUMBER, SCHOOL_NAME, SERVERID)
     ON DELETE CASCADE
     ON UPDATE CASCADE,
 CONSTRAINT CLASS_WITH_MENU_GROUP FOREIGN KEY (MENU_GROUP_NAME, SERVERID)
     REFERENCES MENU_GROUP (MENU_GROUP_NAME, SERVERID)
     ON DELETE CASCADE
     ON UPDATE CASCADE
);

-- connecting a class to a menu, a relationship
-- class number denotes the shorthand for the class, i.e. CS2500
-- defulat emoji will be
CREATE TABLE CLASS_IN_MENU
(CLASS_NUMBER VARCHAR(10) NOT NULL,
 SCHOOL_NAME VARCHAR(20) NOT NULL,
 SERVERID VARCHAR(20) NOT NULL,
 ROLE_ID VARCHAR(20) NOT NULL,
 EMOJIID VARCHAR(20) DEFAULT NULL,
 MENUMSGID VARCHAR(20) NOT NULL,

 PRIMARY KEY (CLASS_NUMBER, SCHOOL_NAME, SERVERID, MENUMSGID),
 CONSTRAINT CLASS_NUMBER_ID FOREIGN KEY (CLASS_NUMBER, SCHOOL_NAME, SERVERID)
     REFERENCES CLASS (CLASS_NUMBER, SCHOOL_NAME, SERVERID),
 CONSTRAINT CLASS_IN_MENU_ID FOREIGN KEY (MENUMSGID)
     REFERENCES MENU (MENUMSGID)
);

